# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    http_client:
        scoped_clients:
            twilioApiClient:
                base_uri: 'https://api.twilio.com'
                auth_basic: '%twilio.account_sid%:%twilio.auth_token%'
                
            vonageApiClient:
                base_uri: 'https://rest.nexmo.com'
                auth_basic: '%vonage.api_key%:%vonage.api_secret%'
                
            pushyApiClient:
                base_uri: 'https://api.pushy.me'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
